#!/usr/bin/env python3
"""
ContextRecoveryHook - PreCompact Handler
Runs BEFORE context compaction to:
  1. Backup the full transcript
  2. Generate a structured context summary (.claude/CONTEXT.md)
  3. Update TODO.md with current work state
  4. Log the event to .claude/logs/pre_compact.json
"""
import argparse
import json
import os
import re
import shutil
import sys
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

# ── helpers ──────────────────────────────────────────────────────────────────

def read_stdin() -> dict:
    raw = sys.stdin.read()
    if not raw.strip():
        return {}
    return json.loads(raw)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def safe_read(path: Path, limit: int = 0) -> str:
    """Read file safely. If limit > 0, truncate to that many chars."""
    if not path.exists():
        return ""
    try:
        text = path.read_text(encoding="utf-8")
        return text if limit == 0 else text[:limit]
    except Exception:
        return ""


def safe_write(path: Path, content: str) -> None:
    try:
        ensure_dir(path.parent)
        path.write_text(content, encoding="utf-8")
    except Exception as e:
        print(f"[pre_compact] WARNING: failed to write {path}: {e}", file=sys.stderr)


def format_timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ── core logic ────────────────────────────────────────────────────────────────

def backup_transcript(transcript_path: str, trigger: str) -> Optional[Path]:
    """Copy transcript to .claude/logs/transcript_backups/ with timestamp."""
    src = Path(transcript_path).expanduser()
    if not src.exists():
        return None

    backup_root = Path.home() / ".claude" / "logs" / "transcript_backups"
    ensure_dir(backup_root)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_name = f"transcript_{trigger}_{ts}.jsonl"
    dst = backup_root / backup_name

    try:
        shutil.copy2(src, dst)
        return dst
    except Exception as e:
        print(f"[pre_compact] WARNING: backup failed: {e}", file=sys.stderr)
        return None


def rotate_backups(backup_root, max_count=10, max_age_days=7):
    """Keep newest max_count backups and any from last max_age_days. Delete rest."""
    try:
        backups = sorted(backup_root.glob("transcript_*.jsonl"),
                         key=lambda p: p.stat().st_mtime,
                         reverse=True)
        if len(backups) <= max_count:
            return

        cutoff = datetime.now() - timedelta(days=max_age_days)
        kept = set(backups[:max_count])  # Always keep newest max_count

        # Also keep any from last max_age_days
        for p in backups:
            if datetime.fromtimestamp(p.stat().st_mtime) >= cutoff:
                kept.add(p)

        to_delete = [p for p in backups if p not in kept]
        for p in to_delete:
            try:
                p.unlink()
            except Exception:
                pass

        if to_delete:
            print(f"[pre_compact] Cleaned {len(to_delete)} old backup(s)", file=sys.stdout)
    except Exception:
        pass  # Rotation is best-effort


def extract_key_content(transcript_path: str) -> dict:
    """Extract meaningful content from transcript for context generation."""
    transcript = safe_read(Path(transcript_path), limit=50_000)

    # Extract user prompts (look for role:user patterns in JSONL)
    prompts = re.findall(r'"message"\s*:\s*"((?:[^"\\]|\\.)*)"', transcript)
    cleaned_prompts = []
    for p in prompts[-10:]:  # last 10 messages
        # Unescape JSON string
        p = p.encode().decode("unicode_escape", errors="replace")
        p = p.replace("\\n", "\n").replace('\\"', '"')
        if len(p) > 10:
            cleaned_prompts.append(p[:500])

    # Extract file paths mentioned in tool results
    files = re.findall(r'[\w\-\./]+\.(py|ts|tsx|js|jsx|md|json|yaml|yml|go|rs|java|cpp|c|h|toml)\b',
                       transcript)
    unique_files = list(dict.fromkeys(files))[-20:]  # last 20 unique files

    return {
        "prompts": cleaned_prompts,
        "files": unique_files,
    }


def generate_context_summary(transcript_path: str, session_id: str) -> str:
    """Generate a structured context summary for .claude/CONTEXT.md."""
    data = extract_key_content(transcript_path)

    lines = [
        f"# Claude Code Session Context",
        f"> Auto-generated by ContextRecoveryHook at {format_timestamp()}",
        f"> **DO NOT EDIT** — this file is auto-generated before compaction.",
        "",
        "---",
        "",
        "## Session Info",
        f"- **Session ID**: `{session_id[:8]}...`",
        f"- **Generated**: {format_timestamp()}",
        "",
        "## Recent Work",
    ]

    if data["prompts"]:
        lines.append("### Recent User Requests")
        for p in data["prompts"][-5:]:
            escaped = p.replace("|", "\\|").replace("\n", " ")[:300]
            lines.append(f"- {escaped}")
    else:
        lines.append("_No recent prompts extracted._")

    if data["files"]:
        lines.append("")
        lines.append("### Files Recently Touched")
        lines.append("```")
        lines.append(", ".join(f"`{f}`" for f in data["files"]))
        lines.append("```")

    lines.extend([
        "",
        "## Recovery Notes",
        "",
        "_Add your notes here before the next session — what was in progress,",
        "_what files to revisit, what decisions were made, etc._",
        "",
        "---",
        f"> Generated by ContextRecoveryHook · {format_timestamp()}",
    ])

    return "\n".join(lines)


def update_todo_state() -> bool:
    """Update .claude/TODO.md with current timestamp to signal session continuity."""
    todo_path = Path.home() / ".claude" / "TODO.md"
    if not todo_path.exists():
        return False

    content = todo_path.read_text(encoding="utf-8")
    # Ensure the file has a "Last Updated" line
    if "<!-- last-updated:" not in content:
        marker = f"\n<!-- last-updated: {format_timestamp()} -->\n"
        todo_path.write_text(content.rstrip() + marker, encoding="utf-8")
    else:
        content = re.sub(
            r"<!-- last-updated: [^>]+ -->",
            f"<!-- last-updated: {format_timestamp()} -->",
            content,
        )
        todo_path.write_text(content, encoding="utf-8")
    return True


def log_event(event_type: str, data: dict) -> None:
    """Append to .claude/logs/events.json."""
    log_root = Path.home() / ".claude" / "logs"
    ensure_dir(log_root)
    log_file = log_root / "events.json"

    events = []
    if log_file.exists():
        try:
            events = json.loads(log_file.read_text(encoding="utf-8"))
        except Exception:
            events = []

    events.append({
        "type": event_type,
        "timestamp": format_timestamp(),
        **data,
    })

    # Keep last 100 events
    events = events[-100:]
    log_file.write_text(json.dumps(events, indent=2, ensure_ascii=False), encoding="utf-8")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="ContextRecoveryHook PreCompact")
    parser.add_argument("--backup", action="store_true",
                        help="Create transcript backup")
    parser.add_argument("--generate-context", action="store_true",
                        help="Generate CONTEXT.md summary")
    parser.add_argument("--verbose", action="store_true",
                        help="Print verbose output")
    args = parser.parse_args()

    input_data = read_stdin()

    session_id = input_data.get("session_id", "unknown")
    transcript_path = input_data.get("transcript_path", "")
    trigger = input_data.get("trigger", "unknown")
    custom_instructions = input_data.get("custom_instructions", "")

    results = {}

    # 1. Backup transcript
    if args.backup and transcript_path:
        backup_path = backup_transcript(transcript_path, trigger)
        if backup_path:
            results["backup"] = str(backup_path)
            if args.verbose:
                print(f"Transcript backed up to: {backup_path}", file=sys.stdout)
            # Rotate: keep newest 10 + any from last 7 days
            backup_root = Path.home() / ".claude" / "logs" / "transcript_backups"
            rotate_backups(backup_root)

    # 2. Generate context summary
    if args.generate_context and transcript_path:
        summary = generate_context_summary(transcript_path, session_id)
        context_path = Path.home() / ".claude" / "CONTEXT.md"
        safe_write(context_path, summary)
        results["context_generated"] = str(context_path)
        if args.verbose:
            print(f"Context summary written to: {context_path}", file=sys.stdout)

    # 3. Update TODO state
    update_todo_state()

    # 4. Log event
    log_event("pre_compact", {
        "session_id": session_id,
        "trigger": trigger,
        "custom_instructions": custom_instructions,
        "results": results,
    })

    if args.verbose:
        print(f"PreCompact handler done. trigger={trigger}, session={session_id[:8]}...",
              file=sys.stdout)

    sys.exit(0)


if __name__ == "__main__":
    main()
