#!/usr/bin/env python3
"""
ContextRecoveryHook - Setup Handler
Runs once on first session to initialize directory structure and template files.
Safe to run multiple times (idempotent).
"""
import json
import sys
from datetime import datetime
from pathlib import Path


def format_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def ensure_dir(path):
    path.mkdir(parents=True, exist_ok=True)


def write_if_missing(path, content):
    if not path.exists():
        try:
            ensure_dir(path.parent)
            path.write_text(content, encoding="utf-8")
            print(f"[setup] Created: {path}", file=sys.stdout)
            return True
        except Exception as e:
            print(f"[setup] WARNING: failed to create {path}: {e}", file=sys.stderr)
    return False


def log_event(event_type, data):
    log_root = Path.home() / ".claude" / "logs"
    ensure_dir(log_root)
    log_file = log_root / "events.json"
    events = []
    if log_file.exists():
        try:
            events = json.loads(log_file.read_text(encoding="utf-8"))
        except Exception:
            events = []
    events.append({
        "type": event_type,
        "timestamp": format_timestamp(),
        **data,
    })
    events = events[-100:]
    log_file.write_text(json.dumps(events, indent=2, ensure_ascii=False), encoding="utf-8")


def setup_init():
    """Initialize .claude/ directory structure and template files."""
    home = Path.home()
    claude_dir = home / ".claude"

    # Create directory structure
    ensure_dir(claude_dir / "logs")
    ensure_dir(claude_dir / "logs" / "transcript_backups")

    # Template: CONTEXT.md
    context_path = claude_dir / "CONTEXT.md"
    write_if_missing(context_path, f"""# Claude Code Session Context
> Auto-generated by ContextRecoveryHook on {format_timestamp()}
> **DO NOT EDIT** — this file is auto-generated before compaction.

---
> Generated by ContextRecoveryHook · {format_timestamp()}
""")

    # Template: TODO.md
    todo_path = claude_dir / "TODO.md"
    write_if_missing(todo_path, f"""# TODO

<!-- last-updated: {format_timestamp()} -->

- [ ] Add your active work items here
- [ ] Format: - [ ] Task description

---

> Add unchecked items above. Completed items can be marked with [x].
""")

    # Marker file to track that setup has run
    marker_path = claude_dir / ".context-recovery-setup"
    write_if_missing(marker_path, f"setup_completed={format_timestamp()}\n")

    log_event("setup", {
        "initialized": True,
        "claude_dir": str(claude_dir),
    })

    # Output additionalContext to welcome the user
    output = {
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": f"""## ContextRecoveryHook Initialized

Welcome! ContextRecoveryHook has been set up in `~/.claude/`.

**Created files:**
- `~/.claude/CONTEXT.md` — auto-generated context summary (before compaction)
- `~/.claude/TODO.md` — manual TODO list for work continuity
- `~/.claude/logs/events.json` — event log
- `~/.claude/logs/transcript_backups/` — transcript backups

**What it does:**
- PreCompact: backs up transcript + generates CONTEXT.md before context compression
- SessionStart: injects saved context into the new session

**Next:** Edit `~/.claude/TODO.md` to add your active work items!
""",
        }
    }
    print(json.dumps(output), file=sys.stdout)
    sys.exit(0)


def main():
    # Check if already set up
    marker = Path.home() / ".claude" / ".context-recovery-setup"
    if marker.exists():
        sys.exit(0)  # Already initialized, do nothing
    setup_init()


if __name__ == "__main__":
    main()
